Introduction about Numpy 
---

In [14]:
import numpy as np

In [10]:
np.__version__

'1.20.1'

In [9]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000019A43B21B20>, toplevel='numpy')>

In [12]:
#List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [14]:
print(a+b)
print(a*b)


#Eror dikarenakan hal-hal berikut:
#Dalam list tidak bisa dimultiplay
#Dimana dalam list hanya ditambahkan dari variabel a ke variabel b yang kemudian menjadi list baru yang isinya variabel a dan b.

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


Contoh 1
--

In [17]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [19]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = a.reshape((3,3))

In [21]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
b * 10 + 4

array([[14, 24, 34],
       [44, 54, 64],
       [74, 84, 94]])

Membuat Numpy Arrays
--

In [26]:
# vector, list
v = np.array([1, 2, 3, 4, 5])

v.shape

(5,)

In [27]:
# matrix, nested list
m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape

(2, 3)

In [28]:
type(v), type(m)

(numpy.ndarray, numpy.ndarray)

In [29]:
a = [1,2,3]

In [32]:
type(a)

list

Perbedaan antara array v dan m hanya dalam bentuknya. Sehingga dalam hal ini kita bisa mendapatkan informasi tentang bentuk array dengan menggunakan ndarray.shape

In [33]:
v.shape

(5,)

In [34]:
m.shape

(2, 3)

In [35]:
m.size

6

Array Menggunakan dtype
--

In [38]:
one_dimension = np.array([1, 2, 3])

two_dimension = np.array([[4, 5, 6],
                          [7, 8, 9]])

In [39]:
one_dimension.shape

(3,)

In [40]:
two_dimension.shape

(2, 3)

Latihan 1
---

Soal:

1. Membuat array 1 dimensi 7, 
2. Membuat array 2 dimensi 3, 3
3. Membuat array 3 dimensi 4, 4, 4

In [36]:
# Membuat array 1 dimensi 7
soal_1 = np.array([1, 2, 3, 4, 5, 6, 7])

In [37]:
soal_1.shape

(7,)

In [42]:
# Membuat array 2 dimensi 3, 3
soal_2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [43]:
soal_2.shape

(3, 3)

In [55]:
# Membuat array 2 dimensi 4, 4, 4
soal_3 = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [10, 11, 12, 13],
                    [14, 15, 16, 17]],
                   
                   [[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [10, 11, 12, 13],
                    [14, 15, 16, 17]],
                   
                   [[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [10, 11, 12, 13],
                    [14, 15, 16, 17]],
                   
                   [[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [10, 11, 12, 13],
                    [14, 15, 16, 17]]])
                
                       

In [56]:
soal_3.shape

(4, 4, 4)

Mendefinisikan tipe data array dengan menggunakan kata kunci dtype seperti `int`, `float`, `complex`, `bool`, `object`dan sebagainya

In [70]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

m

array([[1., 2., 3.],
       [4., 5., 6.]])

Membuat Matrix Zero
---

In [71]:
# One dimension

zeros_matrix = np.zeros(5)

zeros_matrix

array([0., 0., 0., 0., 0.])

In [73]:
#two dimension

zeros_matrix2 = np.zeros(5,2)

#Eror karena harus menggunakan format tuple 

AttributeError: module 'numpy' has no attribute 'zeros2'

In [74]:
# Format Tuple dalam two dimention

zeros_matrix2 = np.zeros((5,2)) # 5 baris, 2 kolom
zeros_matrix2 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Contoh
---

In [ ]:
zeros = np.zeros((7, 7), dtype=int)

# Print zeros
zeros

Membuat Matrix Ones
---

In [75]:
#one dimension

matrix_ones = np.ones(5)
matrix_ones 

array([1., 1., 1., 1., 1.])

In [78]:
#two_dimension

matrix_ones2 = np.ones((5,2)) # 5 baris, 2 kolom
matrix_ones2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [76]:
#three dimension

matrix_ones3 = np.ones((3, 4, 2)) #3 rows, 4 columns, 2 depth
matrix_ones3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

Contoh 
---

In [ ]:
ones = np.ones((4, 4, 4, 4), dtype=int)

# Print ones
ones

In [ ]:
ones = np.ones((4, 4, 4), dtype=int)

# Print ones
ones

In [ ]:
ones = np.ones((4), dtype=int)

# Print ones
ones

In [ ]:
ones = np.ones((4, 7), dtype=int)

# Print ones
ones

In [ ]:
ones = np.ones((7, 7), dtype=int)

# Print ones
ones

In [80]:
one_zero = np.array([[1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1],
                     [0, 1, 0, 1, 0, 1, 0],
                     [1, 0, 1, 0, 1, 0, 1]])
one_zero.shape

(7, 7)

Latihan 2
---

1. Buatlah matriks dari list yang memiliki 4 baris dan 3 kolom

In [81]:
soal_matrix_1 = np.array([[1,2,3], 
                          [4,5,6], 
                          [7,8,9],
                          [10,11,12]])
soal_matrix_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

2. Buatlah matrix berikut

In [83]:
soal_matrix_2 = np.array([[1,9,0,7],
                          [9,8,1,9],
                          [2,0,2,1]])
soal_matrix_2

array([[1, 9, 0, 7],
       [9, 8, 1, 9],
       [2, 0, 2, 1]])

3. Buatlah matrixm 2D dengan size 10

In [84]:
cara_pertama = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
cara_pertama

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
cara_kedua = np.zeros((2,5))
cara_kedua

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
cara_ketiga = np.array([[1,2], 
                      [3,4],
                      [5,6],
                      [7,8],
                      [9,10]])
cara_ketiga

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [89]:
cara_keempat = np.array([[1],
                       [2],
                       [3],
                       [4],
                       [5],
                       [6],
                       [7],
                       [8],
                       [9],
                       [10]])
cara_keempat

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

4. Buatlah matriks 3D yang memiliki 2 baris, 3 kolom, dan 3 dept

In [93]:
soal_matrix_4 = np.array([[[1,2,3],
                           [4,5,6],
                           [7,8,9]],
                          
                          [[9,8,7],
                           [4,5,6],
                           [3,2,1]]])
soal_matrix_4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [4, 5, 6],
        [3, 2, 1]]])

In [94]:
soal_matrix_4.shape

(2, 3, 3)

5. Buatlah array berikut dari zero array dengan for loop

In [10]:
soal_matrix_5 = np.zeros((5,3))
soal_matrix_5

NameError: name 'np' is not defined

In [99]:
for i in soal_matrix_5:
    print(i+9)

[9. 9. 9.]
[9. 9. 9.]
[9. 9. 9.]
[9. 9. 9.]
[9. 9. 9.]


Array-Generating Functions
---

Untuk array yang lebih besar, tidak praktis menginisialisasi data secara manual menggunakan daftar python eksplisit. Sebagai gantinya kita dapat menggunakan salah satu dari banyak fungsi di numpy yang menghasilkan array dari berbagai bentuk seperti:

Range
--

In [21]:
# Membuat range
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


Contoh

In [106]:
x = np.arange(10, 40) # arguments: start, stop

x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [107]:
x = np.arange(10, 40, 4) # arguments: start, stop, step

x

array([10, 14, 18, 22, 26, 30, 34, 38])

In [9]:
x = np.arange(-1, 1, 0.1)

x

NameError: name 'np' is not defined

Angka 9.00000000e-01 sudah merupakan angka floating point. Ini ditulis dalam notasi ilmiah dan setara dengan 9 * 10**-1 atau 0,9.

Linspace
--

In [108]:
# Dalam menggunakan linspace, kedua titik akhir disertakan
np.linspace(0, 10, 10) #Tidak seperti range yang menggunakan step, linspace menggunakan jumlah sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

Random Data
--

In [16]:
from numpy import random

In [8]:
#Bilangan acak seragam [0,1]
random. rand(5,5)

NameError: name 'random' is not defined

In [112]:
# bilangan acak terdistribusi normal standar
x = random.randn(5,5)
x

array([[ 0.65366227, -0.92935042,  1.04333244,  0.39170426,  1.80021414],
       [-2.54068824, -1.97424567, -0.02942376,  0.06865831,  1.24886898],
       [-0.73829077, -0.74664403,  0.05606778, -0.33146945, -0.42873709],
       [-0.7237869 , -0.55747699, -0.95744178,  0.77748701,  0.16893674],
       [-0.01348923, -0.86215583,  0.46264889, -0.34656497, -1.20660574]])

In [113]:
x.dtype

dtype('float64')

In [115]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [116]:
random.randint(10)

0

In [5]:
random.randint(2, 10, size=4)

NameError: name 'random' is not defined

In [20]:
random.randint(2, 10, size=(4,2,2))

array([[[4, 8],
        [7, 6]],

       [[5, 5],
        [2, 5]],

       [[2, 8],
        [6, 5]],

       [[7, 7],
        [5, 7]]])

Latihan 3
---

1. Buatlah array 1-D yang berisi 5 bilangan bulat acak dari 0 hingga 100:

In [19]:
random.randint(0,100, size=5)

array([35, 12, 97, 51, 85])

In [ ]:
2. Buatlah array 2-D dengan 3 baris, setiap baris berisi 5 bilangan bulat acak dari 0 hingga 100

In [18]:
random.randint(0, 100, size=(5,5))

array([[71, 14, 87, 65,  0],
       [27, 27, 79, 92, 96],
       [ 0, 47, 68, 33, 53],
       [54, 92,  5, 29, 90],
       [95, 93, 52, 63, 38]])

In [23]:
x

array([10, 14, 18, 22, 26, 30, 34, 38])