In [1]:
# Import Numpy library
import numpy as np

In [3]:
#  Array satu dimensi
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [4]:
# Aray dua dimensional
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

Cara Mengecek Dimensi
--

In [6]:
print("dimensi pertama:", a.ndim)

print("dimensi kedua:", b.ndim)

dimensi pertama: 1
dimensi kedua: 2


Cara Mengecek Shape
--

In [7]:
print("dimensi pertama:", a.shape)

print("dimensi kedua:", b.shape)

dimensi pertama: (3,)
dimensi kedua: (2, 3)


Cara Mengecek dtype
--

In [8]:
print("dimensi pertama:", a.dtype)

print("dimensi kedua:", b.dtype)

dimensi pertama: int32
dimensi kedua: int32


Cara Mengecek Size
--

In [9]:
print("dimensi pertama:", a.size)

print("dimensi kedua:", b.size)

dimensi pertama: 3
dimensi kedua: 6


In [12]:
print("dimensi pertama:", a.nbytes)

print("dimensi kedua:", b.nbytes)

dimensi pertama: 12
dimensi kedua: 24


NP.ones and zeros
---

np.ones
--

In [13]:
ones_matrix = np.ones((3, 3, 3), dtype=("int32"))

print(ones_matrix)
ones_matrix.ndim

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


3

Dalam hal ini dimension memiliki kegunaan yakni dimana semakin banyak dimensi maka akan semakin banyak data yang bisa di store ke setiap dimensi tersebut serta membuat data menjadi lebih rapih.

np.zeros
--

In [14]:
zeros_matrix = np.zeros((3, 3, 3),
                        dtype=("int32"))

print(zeros_matrix)
zeros_matrix.ndim

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


3

Np.full and np.rand
---

Np.full
--

In [15]:
full_matrix = np.full((5, 5), 13292)

print(full_matrix)
full_matrix.ndim 

[[13292 13292 13292 13292 13292]
 [13292 13292 13292 13292 13292]
 [13292 13292 13292 13292 13292]
 [13292 13292 13292 13292 13292]
 [13292 13292 13292 13292 13292]]


2

In [16]:
random_matrix = np.random.rand(5, 5)

print(random_matrix)
random_matrix.ndim 

[[0.10797595 0.5181113  0.13990434 0.80012396 0.06501015]
 [0.48236874 0.18099769 0.30397529 0.34566224 0.90589387]
 [0.49408632 0.06427625 0.63942409 0.54831696 0.00375383]
 [0.04631949 0.13486254 0.55599755 0.64289475 0.3219973 ]
 [0.96261216 0.12021597 0.73334905 0.75096067 0.86229888]]


2

Np.randonm
--

In [17]:
np.random.randint(-2, 6, size=(3, 3, 3))

array([[[-2,  0,  1],
        [ 5,  3,  4],
        [-1,  1,  2]],

       [[-1,  3,  2],
        [-2,  1, -2],
        [ 3, -1,  0]],

       [[ 4,  4,  0],
        [ 2,  1,  5],
        [ 5,  3,  0]]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Slicing
---

In [19]:
# Define variable
for_slicing = np.random.randint(-2, 6, size=(3, 3))

# Output check
for_slicing

array([[ 4,  0,  5],
       [ 5, -1,  0],
       [-2,  4,  3]])

In [20]:
for_slicing[1, 2] # Variable[baris keberapa, kolom keberapa]

0

In [21]:
for_slicing[0, 2]

5

In [22]:
for_slicing[2, 1]

4

In [23]:
# Define variable
for_slicing_2 = np.random.randint(0, 10, size=(5, 5, 5))

# Output check
for_slicing_2

array([[[4, 2, 9, 2, 1],
        [5, 3, 7, 8, 1],
        [2, 6, 4, 7, 6],
        [5, 7, 3, 4, 9],
        [1, 6, 3, 5, 9]],

       [[9, 4, 0, 6, 4],
        [0, 6, 1, 6, 8],
        [4, 6, 4, 4, 9],
        [2, 0, 2, 3, 5],
        [8, 6, 7, 2, 7]],

       [[1, 6, 4, 0, 8],
        [1, 4, 4, 2, 6],
        [6, 1, 9, 7, 0],
        [8, 2, 8, 4, 0],
        [7, 5, 8, 4, 3]],

       [[4, 3, 4, 6, 4],
        [1, 3, 5, 6, 3],
        [3, 8, 0, 6, 3],
        [4, 3, 3, 6, 1],
        [7, 9, 4, 4, 5]],

       [[8, 5, 7, 9, 7],
        [0, 8, 8, 4, 9],
        [5, 8, 7, 6, 9],
        [8, 2, 2, 1, 3],
        [0, 7, 1, 6, 5]]])

In [24]:
for_slicing_2[1, 1, 1] # Variable[group,row,column]

6

Special slicing ":"
---

In [26]:
for_slicing_2[:, 1:, 1:]

array([[[3, 7, 8, 1],
        [6, 4, 7, 6],
        [7, 3, 4, 9],
        [6, 3, 5, 9]],

       [[6, 1, 6, 8],
        [6, 4, 4, 9],
        [0, 2, 3, 5],
        [6, 7, 2, 7]],

       [[4, 4, 2, 6],
        [1, 9, 7, 0],
        [2, 8, 4, 0],
        [5, 8, 4, 3]],

       [[3, 5, 6, 3],
        [8, 0, 6, 3],
        [3, 3, 6, 1],
        [9, 4, 4, 5]],

       [[8, 8, 4, 9],
        [8, 7, 6, 9],
        [2, 2, 1, 3],
        [7, 1, 6, 5]]])

In [27]:
for_slicing_2[1:4, 2, 1:4]

array([[6, 4, 4],
       [1, 9, 7],
       [8, 0, 6]])

Mengganti elemen menggunakan metode slicing 
---

In [28]:
for_slicing_2[1, 1, 1] = 2357

# Output
print(for_slicing_2)

[[[   4    2    9    2    1]
  [   5    3    7    8    1]
  [   2    6    4    7    6]
  [   5    7    3    4    9]
  [   1    6    3    5    9]]

 [[   9    4    0    6    4]
  [   0 2357    1    6    8]
  [   4    6    4    4    9]
  [   2    0    2    3    5]
  [   8    6    7    2    7]]

 [[   1    6    4    0    8]
  [   1    4    4    2    6]
  [   6    1    9    7    0]
  [   8    2    8    4    0]
  [   7    5    8    4    3]]

 [[   4    3    4    6    4]
  [   1    3    5    6    3]
  [   3    8    0    6    3]
  [   4    3    3    6    1]
  [   7    9    4    4    5]]

 [[   8    5    7    9    7]
  [   0    8    8    4    9]
  [   5    8    7    6    9]
  [   8    2    2    1    3]
  [   0    7    1    6    5]]]


Latihan 1
---

Buatlah sebuah matrix random float (range angka = 0 - 1) dengan ukuran size 5, 5, 5 lalu slice lah di tiap group row 4(hitungan biasa) dan elemen ke 1-3(hitungan biasa)

In [30]:
latihan_1 = np.random.rand(5, 5, 5)

#variable
print(latihan_1)

print("\n\njawaban: \n ", 
      latihan_1[:, 3, :3])

[[[0.58107405 0.70304928 0.34775789 0.46252314 0.36698881]
  [0.58456749 0.463153   0.4874786  0.27857196 0.4722676 ]
  [0.10842046 0.9286826  0.87633449 0.82374636 0.42800968]
  [0.66852623 0.07706923 0.77954353 0.77540895 0.40639123]
  [0.59292762 0.91141617 0.5000243  0.5748402  0.02853649]]

 [[0.73733354 0.74752952 0.58517979 0.26715222 0.10187582]
  [0.89572049 0.40312174 0.45640136 0.96990406 0.48858255]
  [0.54584442 0.6099089  0.33911944 0.55164346 0.18092047]
  [0.56625087 0.56774103 0.41496334 0.950508   0.47567626]
  [0.09131929 0.3115425  0.23013276 0.70591028 0.38589552]]

 [[0.34075771 0.99368842 0.54660086 0.39650521 0.7125139 ]
  [0.04576385 0.07595227 0.44582534 0.63925558 0.67414673]
  [0.18394405 0.33057565 0.17923387 0.66058133 0.54153571]
  [0.47907846 0.74088815 0.23622262 0.82072154 0.98501962]
  [0.3051051  0.99395596 0.1628349  0.23626062 0.99733219]]

 [[0.21324571 0.25360901 0.40620088 0.04738109 0.44868858]
  [0.71793642 0.0413196  0.77265591 0.59695575 0.9

Stacking
---

Vertical Stacking
--

In [31]:
# variable
v1 = np.ones((3, 3), dtype="int")
v2 = np.zeros((3, 3), dtype="int")

np.vstack([v1, v2, v1, v2])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Horizontal Stacking
--

In [32]:
np.hstack([v1, v2])

array([[1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0]])

Statistics
---

In [34]:
# variable
stats = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Check variable
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.max(stats)

6

In [37]:
np.min(stats)

1

In [36]:
np.median(stats)

3.5

In [38]:
np.mean(stats)

3.5

In [39]:
np.sum(stats)

21

In [40]:
np.sum(stats, axis=1) # Axis 1 adalah baris, axis 0 adalah kolom 

array([ 6, 15])

In [41]:
np.sum(stats, axis=0)

array([5, 7, 9])