In [3]:
import numpy as np

In [15]:
#cara satu

cara_satu = np.zeros((8,8), dtype=int)

for x in range(8):
    for y in range(8):
        if((x+y)%2==1):
            cara_satu[x,y]=cara_satu[x,y]=1

print(cara_satu)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [17]:
#cara dua

cara_dua = np.zeros((8,8), dtype=int) #matrix

cara_dua[1::2, ::2] = 1 # 
cara_dua[::2, ::2] = 1

print(cara_dua)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]
